etcJupyter:
  # Options for Jupyter Notebook itself, set for each user
  jupyter_notebook_config.json: {}

nfsPVC:
  enabled: false
  # If you want a PVC with NFS that can be used to mount home directories
  #nfs:
    #serverIP: fs-d59c0f7f.efs.us-west-2.amazonaws.com # IP of your NFS Server
    #shareName: hackweek-cluster-home-dirs # Path of your NFS share export

jupyterhub:
  prePuller:
    continuous:
      enabled: false
    hook:
      enabled: false
  scheduling:
    userScheduler:
      enabled: false
    userPods:
      nodeAffinity:
        matchNodePurpose: require
  singleuser:
    cloudMetadata:
      enabled: true
    defaultUrl: "/lab"
  hub:
    extraConfig:
      00-jupyterlab: |
        c.Spawner.default_url = '/lab'
      01-hub-config: |
        c.JupyterHub.shutdown_on_logout = True

    # z2jh customizations go here

rbac:
  enabled: true
  serviceAccountName: "jovyan"
  serviceAccountRoleArn: "arn:aws:iam::783380859522:role/icesat2-hackweek-bucket-access-serviceaccount"
